// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type UserUserBase struct {
	UserID         int64            `json:"user_id"`
	UserEmail      string           `json:"user_email"`
	UserPassword   string           `json:"user_password"`
	UserSalt       string           `json:"user_salt"`
	UserLoginTime  pgtype.Timestamp `json:"user_login_time"`
	UserLogoutTime pgtype.Timestamp `json:"user_logout_time"`
	UserLoginIp    pgtype.Text      `json:"user_login_ip"`
	UserCreatedAt  pgtype.Timestamp `json:"user_created_at"`
	UserUpdatedAt  pgtype.Timestamp `json:"user_updated_at"`
}

type UserUserVerify struct {
	VerifyID        int64            `json:"verify_id"`
	VerifyOtp       string           `json:"verify_otp"`
	VerifyKey       string           `json:"verify_key"`
	VerifyKeyHash   string           `json:"verify_key_hash"`
	IsVerified      pgtype.Bool      `json:"is_verified"`
	IsDeleted       pgtype.Bool      `json:"is_deleted"`
	VerifyCreatedAt pgtype.Timestamp `json:"verify_created_at"`
	VerifyUpdatedAt pgtype.Timestamp `json:"verify_updated_at"`
}
