// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repo

import (
	"context"
)

type Querier interface {
	CheckUserBaseExists(ctx context.Context, userEmail string) (int64, error)
	CreateUserVerify(ctx context.Context, arg CreateUserVerifyParams) (UserUserVerify, error)
}

var _ Querier = (*Queries)(nil)
