// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user_verify.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserVerify = `-- name: CreateUserVerify :one
INSERT INTO "user"."user_verify" (
    "verify_otp",
    "verify_key",
    "verify_key_hash"
) VALUES ($1, $2, $3) RETURNING verify_id, verify_otp, verify_key, verify_key_hash, is_verified, is_deleted, verify_created_at, verify_updated_at
`

type CreateUserVerifyParams struct {
	VerifyOtp     string `json:"verify_otp"`
	VerifyKey     string `json:"verify_key"`
	VerifyKeyHash string `json:"verify_key_hash"`
}

func (q *Queries) CreateUserVerify(ctx context.Context, arg CreateUserVerifyParams) (UserUserVerify, error) {
	row := q.db.QueryRow(ctx, createUserVerify, arg.VerifyOtp, arg.VerifyKey, arg.VerifyKeyHash)
	var i UserUserVerify
	err := row.Scan(
		&i.VerifyID,
		&i.VerifyOtp,
		&i.VerifyKey,
		&i.VerifyKeyHash,
		&i.IsVerified,
		&i.IsDeleted,
		&i.VerifyCreatedAt,
		&i.VerifyUpdatedAt,
	)
	return i, err
}

const getUserVerifyByKeyHash = `-- name: GetUserVerifyByKeyHash :one
SELECT verify_id, verify_otp, verify_key, verify_key_hash, is_verified, is_deleted, verify_created_at, verify_updated_at
FROM "user"."user_verify"
WHERE "verify_key_hash" = $1
`

func (q *Queries) GetUserVerifyByKeyHash(ctx context.Context, verifyKeyHash string) (UserUserVerify, error) {
	row := q.db.QueryRow(ctx, getUserVerifyByKeyHash, verifyKeyHash)
	var i UserUserVerify
	err := row.Scan(
		&i.VerifyID,
		&i.VerifyOtp,
		&i.VerifyKey,
		&i.VerifyKeyHash,
		&i.IsVerified,
		&i.IsDeleted,
		&i.VerifyCreatedAt,
		&i.VerifyUpdatedAt,
	)
	return i, err
}

const updateUserVerify = `-- name: UpdateUserVerify :one
UPDATE "user"."user_verify"
SET 
    is_verified = COALESCE($1, is_verified),
    is_deleted = COALESCE($2, is_deleted)
WHERE verify_key_hash = $3
RETURNING verify_id, verify_otp, verify_key, verify_key_hash, is_verified, is_deleted, verify_created_at, verify_updated_at
`

type UpdateUserVerifyParams struct {
	IsVerified    pgtype.Bool `json:"is_verified"`
	IsDeleted     pgtype.Bool `json:"is_deleted"`
	VerifyKeyHash string      `json:"verify_key_hash"`
}

func (q *Queries) UpdateUserVerify(ctx context.Context, arg UpdateUserVerifyParams) (UserUserVerify, error) {
	row := q.db.QueryRow(ctx, updateUserVerify, arg.IsVerified, arg.IsDeleted, arg.VerifyKeyHash)
	var i UserUserVerify
	err := row.Scan(
		&i.VerifyID,
		&i.VerifyOtp,
		&i.VerifyKey,
		&i.VerifyKeyHash,
		&i.IsVerified,
		&i.IsDeleted,
		&i.VerifyCreatedAt,
		&i.VerifyUpdatedAt,
	)
	return i, err
}
