// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user_profile.sql

package repo

import (
	"context"
)

const createUserProfile = `-- name: CreateUserProfile :one
INSERT INTO "user".user_profile (
    user_id,
    user_email,
    user_nickname
) VALUES ($1, $2, $3) RETURNING user_id, user_email, user_nickname, user_avatar, user_mobile, user_gender, user_birthday, user_created_at, user_updated_at
`

type CreateUserProfileParams struct {
	UserID       int64  `json:"user_id"`
	UserEmail    string `json:"user_email"`
	UserNickname string `json:"user_nickname"`
}

func (q *Queries) CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) (UserUserProfile, error) {
	row := q.db.QueryRow(ctx, createUserProfile, arg.UserID, arg.UserEmail, arg.UserNickname)
	var i UserUserProfile
	err := row.Scan(
		&i.UserID,
		&i.UserEmail,
		&i.UserNickname,
		&i.UserAvatar,
		&i.UserMobile,
		&i.UserGender,
		&i.UserBirthday,
		&i.UserCreatedAt,
		&i.UserUpdatedAt,
	)
	return i, err
}
